#!/bin/bash
cp $HOME/.homesick/repos/vimfiles/home/.vimrc.local $HOME/.homesick/repos/dotfiles/backups/
cp $HOME/mm.cfg $HOME/.homesick/repos/dotfiles/backups/
cp -R $HOME/Documents/machines/terminal-themes/ $HOME/.homesick/repos/dotfiles/themes/
